### ISSUE TITLE
강의영상 미노출 문제

### ISSUE THREAD

**Issue by tiramica** [again7536/icampus-manager#48]
교수님들이 유튜브에 본인들 영상을 찍어 올린다음 아이캠퍼스에 연동(?) 하시는데
그래서인지 버그가 발생하는것 같습니다.
밑에 40번 이슈였나 거기서 타입 확인하는 방법대로 들어가보지만 all 뭐시기 그런 문구는 전혀 없네요..!
유튜브라 조금 특이케이스인가... 흠..

**Comment by again7536** [comment]
@tiramica 
youtube 영상은 의도적으로 노출하지 않았는데, 과제란에 임시적으로 노출시키도록 하겠습니다.

**Comment by tiramica** [comment]
감사합니다

**Comment by again7536** [comment]
## 조치 사항
1. youtube 영상이 강의 목록에 올라오도록 변경.
    - 다만 자동 재생 선택은 불가능
