### ISSUE TITLE
[Feature Suggestion] 사용자 임의로 과제 추가

### ISSUE THREAD

**Issue by DailyPS** [again7536/icampus-manager#80]
[Main]
강의컨텐츠에 등록되지 않고, "과제 및 평가" 에 등록되는 과제를 사용자가 직접 추가하고 없앨 수 있는 기능이 있었으면 좋겠습니다.

[Reason]
대부분의 교수님들을 강의컨텐츠 탭에 등록하지만, "과제 및 평가" 에만 등록하시는 교수님들도 꽤 계시고, 이원화가 가능하다보니 가끔씩 과제가 있었다는 사실을 잊는 학우분들도 계십니다.

따라서 아이캠퍼스 강의 수강 및 과제를 관리해주는 아이캠퍼스 매니저에서 해당 부분을 사용자 임의로 관리할 수 있는 부분이 생긴다면, 학우분들의 학업을 보조하는 데 있어 더욱 도움이 될 것 같습니다.

**Comment by again7536** [comment]
기능 제안 감사드립니다.
확인해본 후에 가능할 경우 추가하겠습니다.

**Comment by again7536** [comment]
현재 작업중이고, 내주 중에 배포 예정입니다.

**Comment by again7536** [comment]
@DailyPS 
대부분 개발 완료되어서 공유해드립니다.

### 사용자 추가 과제 선택 모달
![label2](https://user-images.githubusercontent.com/45936642/204073951-275e4417-3646-4d17-85de-82be3e85a5e3.gif)

### 사용자 추가 과제 선택 & 리스트
![label](https://user-images.githubusercontent.com/45936642/204073948-2d0bfe82-42e7-4756-a8e1-6474f8c0bf6b.gif)

**Comment by DailyPS** [comment]
확인했습니다! 기능 추가 감사드립니다!
